# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMRxMRLMPvm9_FeG8C0XvSJrNxIOUY5M
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
import random
dice=0
for i in range(250):
    walk = [0] 
    for x in range(100):
        step = walk[-1] 
        dice = random.randint(1,7)
        if dice <= 2 :
            step = max(0, step - 1)

        elif dice<=5:
            step += 1
        else:
            step = step + random.randint(1,7)
    print(step)